---
site: "Leqa'sblog"
url: "https://testblog.github.io"
baseurl: ''
title: 'Leqa'
description: 'Don gian chi la ghi va chep.'
permalink: 'pretty'
highlighter: 'rouge'
exclude:
  - '.jekyll-cache'
  - 'Gemfile'
  - 'Gemfile.lock'

compress_html:
  clippings: 'all'
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: '_sass'
  style:    ':compressed'

target-blank:
  add_css_classes: external-link

jekyll-mentions:
  base_url: 

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-mentions

collections:
  pages:
    output: true
    permalink: '/:path'
  posts:
    output: true
    permalink: '/:path'
  tags:
    output: true
    permalink: '/tag/:path/'

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "/pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "/posts"
      type: "posts"
    values:
      layout: "post"

jekyll-archives:
  enabled: ['year', 'month']
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
